version: '3.4'
services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  dispatcher:
    restart: "no"
  resource:
    restart: "no"
